---
- name: copy mongodb.repo
  copy: src=mongodb.repo dest=/etc/yum.repos.d/mongodb.repo owner=root

- name: install mongodb
  yum: pkg=mongodb-org

- name: start mongodb
  service: name=mongod state=started
