---
- name: Add Elasticsearch Repository for Kibana
  yum_repository:
    name: elasticsearch
    description: Elasticsearch repository for 8.x packages
    baseurl: https://artifacts.elastic.co/packages/8.x/yum
    gpgcheck: yes
    gpgkey: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    enabled: yes

- name: Install Kibana
  yum:
    name: kibana
    state: present

- name: Fetch Elasticsearch password from AWS Secrets Manager
  set_fact:
    es_password: "{{ lookup('amazon.aws.aws_secret', es_secret_name, region=es_region) }}"
  no_log: true

- name: Configure Kibana
  template:
    src: kibana.yml.j2
    dest: /etc/kibana/kibana.yml
    owner: root
    group: kibana
    mode: 0660
  notify: restart kibana

- name: Start Kibana
  service:
    name: kibana
    state: started
    enabled: yes
