---
- name: copy iptables file
  copy:
   src=iptables
   dest=/etc/sysconfig
   owner=root
   group=root
   mode=0644
  notify: start iptables

- name: add mysqld moji-code
  template: >
   src=my.cnf.j2
   dest=/etc/my.cnf
   owner=root
   group=root
   mode=0644
  notify: start mysqld
