---
- name: install java
  yum: name={{item}} state=present
  with_items: 
   - curl-devel 
   - java-{{java_version}}-openjdk

- name: rpm package install
  yum: name=https://download.elasticsearch.org/elasticsearch/release/org/elasticsearch/distribution/rpm/elasticsearch/{{es_version}}/elasticsearch-{{es_version}}.rpm state=present
