---
- name: install java
  yum: name={{item}} state=present
  with_items: 
   - curl-devel 
   - java-{{java_version}}-openjdk

- copy:
  src=elasticsearch.repo
  dest=/etc/yum.repos.d/elasticsearch.repo
  owner=root
  mode=0755

- name: install elasticsearch
  yum: name=elasticsearch state=latest
