---
- name: Install EPEL and Remi repositories
  yum:
    name:
      - "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ epel_version }}.noarch.rpm"
      - "http://rpms.famillecollet.com/enterprise/remi-release-{{ remi_version }}.rpm"
    state: present

- name: Enable PHP 8.2 Remi repository
  command: yum-config-manager --enable remi-php82
  changed_when: false

- name: Install PHP 8.2 and common extensions
  yum:
    name:
      - php
      - php-devel
      - php-common
      - php-gd
      - php-mbstring
      - php-mysqlnd
      - php-pdo
      - php-pear
      - php-xml
    state: present
    enablerepo: remi-php82
