--- 
- name: epel download and install
  yum: name=http://dl.fedoraproject.org/pub/epel/{{centos}}/x86_64/epel-release-{{epel_version}}.noarch.rpm state=present

- name: remi download and install
  yum: name=http://rpms.famillecollet.com/enterprise/remi-release-{{remi_version}}.rpm state=present

- name: php install
  yum: name={{item}} disablerepo=remi state=present
  with_items:
   - php
   - php-devel
   - php-common
   - php-gd
   - php-mbstring
   - php-mysql
   - php-pdo
   - php-pear
   - php-xml
