---
- name: yum upgrade
  yum: name=* state=latest

- name: install the 'Development tools' package group
  yum: name="@Development tools" state=present

- name: install zlib,zlib-devel,openssl,openssl-devel
  yum: name={{item}} state=latest
  with_items:
   - zlib
   - zlib-devel
   - openssl
   - openssl-devel

- name: install ruby
  yum: name=ruby state=latest

- name: ruby-devel
  yum: name=ruby-devel state=latest

- name: gem install json_pure
  gem: name=json_pure state=latest

