---
kibana_version: 8.15.0
kibana_server_port: 5601
kibana_server_host: "0.0.0.0" # Accessible via SSM tunnel or internal net
elasticsearch_url: "http://localhost:9200"
es_secret_name: "prod/elasticsearch/elastic/password"
es_region: "ap-northeast-1"
